### ISSUE TITLE
Connection.End Causes a "Ready" Function to Be Fired

### ISSUE THREAD

**Issue by dchankhour** [postwait/node-amqp#354]
I have a situation where i'm going to be creating multiple connections to Rabbit.  But i'm try to be smart about the connections and try to remove them if there are no need for it.  However, it seems that when i try to do a conn.disconnect(), the connection actually closes but it reconnects and the conn.on("ready") function is fired back.

Is there a better way to disconnect the TCP connection.

**Comment by mcasimir** [comment]
Same issue

**Comment by Amberlamps** [comment]
`connection.disconnect()` triggers a `ECONNRESET` error and immediately tries to reconnect. Therefore the `ready` event is emitted. In order to disconnect from amqp, I needed to call `connection.destroy()` as well.

Why is this not in the documentation and why is `connection.disconnect()` not working?
